version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: medchain-db
    restart: always
    environment:
      POSTGRES_USER: medchain_user
      POSTGRES_PASSWORD: medchain_pass
      POSTGRES_DB: medchain_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
